const data = {
  products: [
    {
      _id: 0,
      name: "Nike Slim Shirts",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 6,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Hig quality shirts",
    },
    {
      _id: 1,
      name: "Nike Shirts",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 70,
      countInStock: 15,
      brand: "Nike",
      rating: 4.0,
      numReviews: 9,
      description: "Hig quality shirts",
    },
    {
      _id: 2,
      name: "Nike Slim Shirts",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 80,
      countInStock: 30,
      brand: "Nike",
      rating: 3.5,
      numReviews: 15,
      description: "Hig quality shirts",
    },
    {
      _id: 3,
      name: "Nike Slim Shirts",
      category: "shirts",
      image: "/images/p4.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 4.2,
      numReviews: 11,
      description: "Hig quality shirts",
    },
    {
      _id: 4,
      name: "Nike Slim Shirts",
      category: "shirts",
      image: "/images/p5.jpg",
      price: 90,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 50,
      description: "Hig quality shirts",
    },
  ],
};

module.exports.data = data;
