version: "3.8"
services:
  product_mongodb:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
  product:
    volumes:
      - .:/app
    depends_on:
      - product_mongodb
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 6868:6868

volumes:
  db: