export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS";
export const PRODUCT_LIST_REQUEST_FAIL = "PRODUCT_LIST_REQUEST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_REQUEST_SUCCESS =
  "PRODUCT_DETAILS_REQUEST_SUCCESS";
export const PRODUCT_DETAILS_REQUEST_FAIL = "PRODUCT_DETAILS_REQUEST_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const GET_CART_LIST = "GET_CART_LIST";

export const USER_SIGN_IN_REQUEST = "USER_SIGN_IN_REQUEST";
export const USER_SIGN_IN_REQUEST_SUCCESS = "USER_SIGN_IN_REQUEST_SUCCESS";
export const USER_SIGN_IN_REQUEST_FAIL = "USER_SIGN_IN_REQUEST_FAIL";
export const USER_SIGN_OUT = "USER_SIGN_OUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
