export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS";
export const PRODUCT_LIST_REQUEST_FAIL = "PRODUCT_LIST_REQUEST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_REQUEST_SUCCESS =
  "PRODUCT_DETAILS_REQUEST_SUCCESS";
export const PRODUCT_DETAILS_REQUEST_FAIL = "PRODUCT_DETAILS_REQUEST_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const GET_CART_LIST = "GET_CART_LIST";
